# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-24 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=255)),
                ('user_level', models.CharField(default='normal', max_length=45)),
                ('pw_hash', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postee', to='user_dashboard.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='user_dashboard.User'),
        ),
    ]
