# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-24 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default='content'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.IntegerField(),
        ),
    ]
