# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-25 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0003_auto_20190425_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to='user_dashboard.User')),
                ('target_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_post', to='user_dashboard.Post')),
            ],
        ),
    ]
